type: sql.reader
query_or_path: >
with t as (
  select full_name,
        html_url,
        homepage,
        insert_date,
        stargazers_count,
        forks_count,
        unnest(topics) as topic
  from repos
  where insert_date = (select max(insert_date) from repos)
    and list_has(topics, 'cli')
  )

  ,top10_topic as (
  select topic, count(distinct full_name) num_repos
  from t
  group by topic
  order by count(distinct full_name) desc
  limit 10
  )
  ,top10_join as (
      select t.*
      from t join top10_topic on t.topic = top10_topic.topic
  )
  ,final as (
  select *, row_number() over(partition by topic order by stargazers_count desc) as rn
  from top10_join)

  select *
  from final
  where rn <= 20
url:  duckdb:///repos.duckdb
